name = "forward-hub"
main = "src/index.ts"
compatibility_date = "2024-09-10"
account_id = "YOUR_ACCOUNT_ID"
workers_dev = true

[[kv_namespaces]]
binding = "FORWARD"
id = "YOUR_KV_ID"

[vars]
PASSWORD = "YOUR_PASSWORD"

[build]
command = "npm run build"
upload_format = "modules"

[env.production]
workers_dev = false
route = "forward-hub.lzr52o.workers.dev/*"
zone_id = "YOUR_ZONE_ID"
compatibility_date = "2024-09-10"
